import z from "zod"
import { Agent } from "@/agent/agent"
import { AgentManage } from "@/agent/manage"
import { AgentTemplate } from "@/agent/schema"
import { Tool } from "./tool"

const Scope = z.enum(["user", "project"]).default("project")
const Kind = z.enum(["planner", "worker", "verifier", "helper"])

const Generate = z.object({
  description: z.string().min(1),
  scope: Scope.optional(),
  mode: AgentTemplate.RuntimeMode.default("subagent"),
  writes: z.boolean().default(true),
  tools: z.array(z.string().min(1)).optional(),
})

const Save = z.object({
  scope: Scope,
  meta: AgentTemplate.MetaInput,
  identity: z.string().default(""),
  rules: z.string().default(""),
})

const Query = z.object({
  include_hidden: z.boolean().default(false),
  kind: AgentTemplate.Kind.optional(),
  subtype: z.string().min(1).optional(),
})

const Create = z.object({
  scope: Scope.optional(),
  id: z.string().min(1).optional(),
  template: z.string().min(1).optional(),
  kind: Kind,
  subtype: z.string().min(1).optional(),
  identity_name: z.string().min(1),
  persona_name: z.string().min(1),
  description: z.string().min(1),
  role: z.string().min(1).optional(),
  identity: z.string().default(""),
  rules: z.string().default(""),
  tools: z.array(z.string().min(1)).optional(),
  writes: z.boolean().optional(),
})

function id(input: string) {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

function meta(input: z.infer<typeof Generate>, out: Awaited<ReturnType<typeof Agent.generate>>) {
  const name = id(out.identifier) || id(input.description).slice(0, 48) || "agent"
  return AgentTemplate.Meta.parse({
    id: name,
    name: out.identifier,
    role: out.systemPrompt.split(/\n+/)[0]?.slice(0, 240) || `You are the ${out.identifier} agent.`,
    description: out.whenToUse,
    mode: input.mode,
    capability: {
      purpose: name,
      tags: [name],
      cost: "medium",
      writes: input.writes,
    },
    allowed_tools: input.tools ?? [],
    denied_tools: [],
    permission_mode: input.tools ? "custom" : "lax",
  })
}

function action(meta: AgentTemplate.Meta) {
  if (meta.kind !== "worker" && meta.kind !== "verifier" && meta.kind !== "helper") return meta
  return AgentTemplate.Meta.parse({
    ...meta,
    request_footer: meta.request_footer ?? {
      file: meta.kind === "verifier" ? "action-verifier.md" : "action-worker.md",
    },
  })
}

function created(input: z.infer<typeof Create>, base?: AgentManage.Info) {
  const aid = input.id ?? id([input.subtype, input.kind, Date.now().toString(36)].filter(Boolean).join("-"))
  return action(
    AgentTemplate.Meta.parse({
      ...(base?.meta ?? {}),
      id: aid,
      name: `${input.identity_name}-${input.persona_name}`,
      kind: input.kind,
      subtype: input.subtype,
      identity_name: input.identity_name,
      persona_name: input.persona_name,
      role: input.role ?? base?.meta.role ?? `You are ${input.identity_name}-${input.persona_name}.`,
      description: input.description,
      mode: "subagent",
      entry: {
        primary: false,
        delegable: true,
        mentionable: false,
        default: false,
        hidden: true,
      },
      capability: {
        purpose: input.subtype ?? input.kind,
        tags: [input.kind, input.subtype, input.identity_name].filter((item): item is string => !!item),
        cost: base?.meta.capability?.cost ?? "medium",
        writes: input.writes ?? input.kind === "worker",
      },
      runner: input.kind === "planner" ? "protocol" : "chat",
      allowed_tools: input.tools ?? base?.meta.allowed_tools ?? [],
      denied_tools: base?.meta.denied_tools ?? [],
      permission_mode: input.tools ? "custom" : base?.meta.permission_mode ?? "lax",
      inherit_permissions: false,
    }),
  )
}

function label(meta: Pick<AgentTemplate.Meta, "id" | "name" | "identity_name" | "persona_name">) {
  if (meta.identity_name && meta.persona_name) return `${meta.identity_name}-${meta.persona_name}`
  return meta.name || meta.id
}

export const AgentGenerateTool = Tool.define("agent_generate", {
  description:
    "Generate an optimized agent template from a natural language description. Use this before saving a new agent.",
  parameters: Generate,
  async execute(params) {
    const out = await Agent.generate({ description: params.description })
    const item = {
      scope: params.scope ?? "project",
      meta: meta(params, out),
      identity: ["# Identity", "", out.systemPrompt].join("\n"),
      rules: ["# Rules", "", out.whenToUse].join("\n"),
    }
    return {
      title: "Generated agent",
      metadata: {},
      output: JSON.stringify(item, null, 2),
    }
  },
})

export const AgentSaveTool = Tool.define("agent_save", {
  description: "Validate and save an agent template generated by agent_generate.",
  parameters: Save,
  async execute(params) {
    const item = await AgentManage.create({
      ...params,
      meta: AgentTemplate.Meta.parse(params.meta),
    })
    return {
      title: `Saved ${item.id}`,
      metadata: {
        id: item.id,
        source: item.source,
      },
      output: `Saved agent ${item.id} to ${item.dir}`,
    }
  },
})

export const AgentQueryTool = Tool.define("agent_query", {
  description: "Query managed agent templates, including hidden templates when requested.",
  parameters: Query,
  async execute(params) {
    const items = await AgentManage.list()
    const filtered = items
      .filter((item) => params.include_hidden || !item.effective.hidden)
      .filter((item) => !params.kind || item.meta.kind === params.kind)
      .filter((item) => !params.subtype || item.meta.subtype === params.subtype)
      .map((item) => ({
        id: item.id,
        label: label(item.meta),
        name: item.name,
        kind: item.meta.kind,
        subtype: item.meta.subtype,
        hidden: item.effective.hidden,
        delegable: item.effective.entry.delegable,
        description: item.effective.description,
      }))
    return {
      title: "Agent query",
      metadata: {
        count: filtered.length,
      },
      output: JSON.stringify(filtered, null, 2),
    }
  },
})

export const AgentCreateTool = Tool.define("agent_create", {
  description:
    "Create a hidden project or user agent for protocol delegation. Dynamic worker, verifier, and helper agents automatically receive the ActionResult protocol footer.",
  parameters: Create,
  async execute(params) {
    const base = params.template ? await AgentManage.get(params.template).catch(() => undefined) : undefined
    const item = await AgentManage.create({
      scope: params.scope ?? "project",
      meta: created(params, base),
      identity: params.identity || base?.identity || `# Identity\n\n${params.role ?? `You are ${params.identity_name}-${params.persona_name}.`}`,
      rules: params.rules || base?.rules || "# Rules\n\n- Complete the delegated assignment within the stated scope.",
    })
    return {
      title: `Created ${item.id}`,
      metadata: {
        id: item.id,
        kind: item.meta.kind,
        subtype: item.meta.subtype,
        hidden: item.effective.hidden,
        request_footer: item.meta.request_footer,
      },
      output: JSON.stringify(
        {
          id: item.id,
          label: label(item.meta),
          kind: item.meta.kind,
          subtype: item.meta.subtype,
          hidden: item.effective.hidden,
          request_footer: item.meta.request_footer,
          dir: item.dir,
        },
        null,
        2,
      ),
    }
  },
})
