import z from "zod"
import { Agent } from "@/agent/agent"
import { AgentManage } from "@/agent/manage"
import { AgentTemplate } from "@/agent/schema"
import { Tool } from "./tool"

const Scope = z.enum(["user", "project"]).default("project")

const Generate = z.object({
  description: z.string().min(1),
  scope: Scope.optional(),
  mode: AgentTemplate.RuntimeMode.default("subagent"),
  writes: z.boolean().default(true),
  tools: z.array(z.string().min(1)).optional(),
})

const Save = z.object({
  scope: Scope,
  meta: AgentTemplate.MetaInput,
  identity: z.string().default(""),
  rules: z.string().default(""),
})

function id(input: string) {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

function meta(input: z.infer<typeof Generate>, out: Awaited<ReturnType<typeof Agent.generate>>) {
  const name = id(out.identifier) || id(input.description).slice(0, 48) || "agent"
  return AgentTemplate.Meta.parse({
    id: name,
    name: out.identifier,
    role: out.systemPrompt.split(/\n+/)[0]?.slice(0, 240) || `You are the ${out.identifier} agent.`,
    description: out.whenToUse,
    mode: input.mode,
    capability: {
      purpose: name,
      tags: [name],
      cost: "medium",
      writes: input.writes,
    },
    allowed_tools: input.tools ?? [],
    denied_tools: [],
    permission_mode: input.tools ? "custom" : "lax",
  })
}

export const AgentGenerateTool = Tool.define("agent_generate", {
  description:
    "Generate an optimized agent template from a natural language description. Use this before saving a new agent.",
  parameters: Generate,
  async execute(params) {
    const out = await Agent.generate({ description: params.description })
    const item = {
      scope: params.scope ?? "project",
      meta: meta(params, out),
      identity: ["# Identity", "", out.systemPrompt].join("\n"),
      rules: ["# Rules", "", out.whenToUse].join("\n"),
    }
    return {
      title: "Generated agent",
      metadata: {},
      output: JSON.stringify(item, null, 2),
    }
  },
})

export const AgentSaveTool = Tool.define("agent_save", {
  description: "Validate and save an agent template generated by agent_generate.",
  parameters: Save,
  async execute(params) {
    const item = await AgentManage.create({
      ...params,
      meta: AgentTemplate.Meta.parse(params.meta),
    })
    return {
      title: `Saved ${item.id}`,
      metadata: {
        id: item.id,
        source: item.source,
      },
      output: `Saved agent ${item.id} to ${item.dir}`,
    }
  },
})
