#!/usr/bin/env bun

import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { AgentTemplate as Template } from "../src/agent/schema"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")

export async function manifest() {
  const dir = path.join(root, "config", "agents")
  const list = (await fs.promises.readdir(dir, { withFileTypes: true }))
    .filter((item) => item.isDirectory())
    .map((item) => item.name)
    .sort()
  const data = await Promise.all(
    list.map(async (id) => {
      const agent = path.join(dir, id)
      const meta = Template.Meta.parse(await Bun.file(path.join(agent, "meta.json")).json())
      const protocol = meta.protocol
        ? {
            file: meta.protocol.file,
            prompt: await Bun.file(path.join(dir, "..", "protocol", meta.protocol.file)).text(),
          }
        : undefined
      const footer = meta.request_footer
        ? {
            file: meta.request_footer.file,
            prompt: meta.request_footer.file
              ? await Bun.file(path.join(dir, "..", "request-footers", meta.request_footer.file)).text()
              : meta.request_footer.prompt ?? "",
          }
        : undefined
      return {
        id,
        name: meta.name,
        dir: `<package:${id}>`,
        source: "package" as const,
        meta,
        identity: await Bun.file(path.join(agent, "identity.md")).text().catch(() => ""),
        rules: await Bun.file(path.join(agent, "rules.md")).text().catch(() => ""),
        ...(protocol ? { protocol } : {}),
        ...(footer ? { requestFooter: footer } : {}),
      }
    }),
  )
  await Bun.write(
    path.join(root, "src", "agent", "builtin.generated.ts"),
    [
      "// Auto-generated by script/build.ts - do not edit",
      'import type { AgentTemplate } from "./loader"',
      "",
      `export const BUILTIN_AGENTS = ${JSON.stringify(data, null, 2)} satisfies AgentTemplate[]`,
      "",
    ].join("\n"),
  )
  console.log(`Generated builtin agent manifest (${data.length} agents)`)
}

if (import.meta.main) await manifest()
