const BASE = [
  "Catalog entry only. This is not a native tool and cannot be called directly.",
  "To use this capability, call the native `AgentProtocolOutput` tool exactly once and declare an Agent Protocol DSL action.",
  'Set that action\'s `executor.type` to `tool` and `executor.target` to this catalog id.',
  "Set that action's `input` to a JSON object that matches the input schema below.",
  "Never call this catalog id as a provider/native tool, and never output provider-specific invocation syntax, XML invoke tags, or textual tool-call syntax.",
]

const MAP: Record<string, string[]> = {
  invalid: ["Do not use this tool."],
  bash: [
    "Run a terminal command when the task needs a shell operation such as git, package scripts, tests, build commands, process inspection, or project commands.",
    "Do not use this tool for ordinary file reading, file writing, editing, filename discovery, or content search when a dedicated protocol tool is available.",
    "Use `workdir` instead of embedding `cd ... && ...` in the command when a different directory is needed.",
    "Write a short `description` that names what the command does.",
    "For independent shell operations, declare multiple independent protocol actions instead of combining unrelated commands into one action.",
  ],
  read: [
    "Read a file or directory from the local filesystem.",
    "Use an absolute `filePath` when available.",
    "Use `offset` and `limit` when only a later or smaller section is needed.",
    "For multiple known files, declare multiple independent protocol actions with `executor.target: \"read\"`.",
  ],
  glob: [
    "Find files by filename pattern.",
    "Use this when exact file paths are unknown and the next step depends on discovering candidate paths.",
    "Set `pattern` to the same glob pattern you would use for normal file discovery.",
  ],
  grep: [
    "Search file contents with a regular expression.",
    "Use this when you need to locate files or lines containing specific text or code patterns.",
    "Use `include` when the search should be limited to specific file types or directories.",
  ],
  edit: [
    "Edit an existing file by replacing exact text.",
    "Use this only when a code or text change is required by the user request.",
    "Read the relevant file content first unless the exact old text is already available in prior runtime observations.",
  ],
  write: [
    "Write a file when creating or replacing complete file content is required.",
    "Use this only when the user request requires a file write.",
    "Prefer edit-style changes for small modifications to existing files.",
  ],
  multiedit: [
    "Apply multiple exact replacements to one file.",
    "Use this only when several coordinated edits are required in the same file.",
    "Read the relevant file content first unless every old string is already available in prior runtime observations.",
  ],
  apply_patch: [
    "Apply a patch to files when a patch-shaped edit is the clearest representation.",
    "Use this only when code or text changes are required.",
  ],
  task: [
    "Delegate a bounded semantic subtask to another agent.",
    "Use this for delegation, not for basic file reads, searches, edits, or shell commands.",
  ],
  todowrite: [
    "Update the visible task list for multi-step work.",
    "Use this only when tracking progress is useful for the current user request.",
  ],
  todoread: ["Read the visible task list."],
  webfetch: ["Fetch and inspect web content from a URL when external web context is required."],
  websearch: ["Search the web when current external information is required."],
  workflow_create: [
    "Create a persisted workflow DAG.",
    "Use this only when the user explicitly asks to create or define a workflow.",
  ],
  workflow_start: [
    "Start a persisted workflow DAG.",
    "Use this only after a workflow exists and the user request requires running it.",
  ],
  agent_generate: ["Generate an agent template from a natural language description."],
  agent_save: ["Validate and save an agent template generated by `agent_generate`."],
}

export namespace ProtocolToolCatalog {
  export function describe(input: { id: string; description: string }) {
    return [...BASE, ...(MAP[input.id] ?? clean(input.description))].join("\n")
  }

  function clean(description: string) {
    const lines = description
      .split("\n")
      .map((line) => line.trimEnd())
      .filter((line) => keep(line))
      .slice(0, 24)
    if (lines.length === 0) return ["Use this runtime capability when its schema and name match the required work."]
    return lines
  }

  function keep(line: string) {
    const text = line.toLowerCase()
    if (text.includes("tool call")) return false
    if (text.includes("call this tool")) return false
    if (text.includes("use the ") && text.includes(" tool")) return false
    if (text.includes("bash tool")) return false
    if (text.includes("read tool")) return false
    if (text.includes("grep tool")) return false
    if (text.includes("glob tool")) return false
    if (text.includes("edit tool")) return false
    if (text.includes("write tool")) return false
    return true
  }
}
